name: CD • Release (main)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: release‑main
  cancel-in-progress: true

env:
  DOTNET_VERSION: 8.0.x

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: GitVersion
        id: ver
        run: |
          dotnet tool install --global gitversion.tool
          gitversion /output json /showvariable FullSemVer >> $GITHUB_OUTPUT

      - name: Publish win‑x64
        run: dotnet publish ./Log_Parser_App.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish/

      - name: Create GitHub Release
        id: rel
        uses: actions/create-release@v1
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        with:
          tag_name: v${{ steps.ver.outputs.FullSemVer }}
          release_name: Release v${{ steps.ver.outputs.FullSemVer }}
          body: "Automated release of version v${{ steps.ver.outputs.FullSemVer }}"
          draft: false
          prerelease: false

      - name: Upload EXE
        uses: actions/upload-release-asset@v1
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        with:
          upload_url: ${{ steps.rel.outputs.upload_url }}
          asset_path: ./publish/Log_Parser_App.exe
          asset_name: Log_Parser_App_v${{ steps.ver.outputs.FullSemVer }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
