name: Auto PR dev → main

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr_dev_to_main:
    
    if: >
      github.event.pull_request.base.ref == 'dev' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create Pull Request dev → main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto Merge: dev → main'
          body: |
            This Pull Request was automatically created after PR #${{ github.event.pull_request.number }} was approved in the dev branch.
          base: main
          head: dev
          draft: false
