# .github/workflows/ci-and-release.yml
name: CI + Sonar + Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: 8.0.x
  SONAR_ORG: blesseddayss
  SONAR_PROJ: BlessedDayss_Log_Parser_App
  PROJECT_NAME: Log_Parser_App

jobs:
  sonar:
    name: Build · Test · SonarCloud Analysis
    runs-on: windows-latest
    outputs:
      FULL_SEM_VER: ${{ steps.version.outputs.fullSemVer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore -c Release

      - name: Run tests with coverage
        run: |
          dotnet test ./Log_Parser_App.Tests/Log_Parser_App.Tests.csproj \
            -c Release --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=coverage.opencover.xml

      - name: Install GitVersion action
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.x'

      - name: Determine semantic version
        id: version
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true

      - name: SonarCloud Begin
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: ${{ env.SONAR_ORG }}
          projectKey: ${{ env.SONAR_PROJ }}
          extraProperties: |
            sonar.cs.opencover.reportsPaths=coverage.opencover.xml
            sonar.coverage.exclusions=**/Migrations/**
            sonar.cpd.exclusions=**/*.generated.cs    # не анализировать autogenerated
            sonar.duplicatedBlocksThreshold=10       # порог дублирования
            sonar.qualitygate.wait=true              # ждать результата Quality Gate


      - name: SonarCloud End
        if: always()
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: ${{ env.SONAR_ORG }}
          projectKey: ${{ env.SONAR_PROJ }}

  
  release:
    name: Publish Release
    runs-on: windows-latest
    needs: sonar
    if: needs.sonar.result == 'success' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish single-file executable
        run: dotnet publish ./Log_Parser_App.csproj \
          -c Release \
          -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o publish/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.sonar.outputs.FULL_SEM_VER }}
          release_name: Release v${{ needs.sonar.outputs.FULL_SEM_VER }}
          body: |
            Automated release of version v${{ needs.sonar.outputs.FULL_SEM_VER }}
          draft: false
          prerelease: false

      - name: Upload executable
        run: |
          gh release upload \
            --repo ${{ github.repository }} \
            --tag v${{ needs.sonar.outputs.FULL_SEM_VER }} \
            publish/Log_Parser_App.exe \
            --clobber